# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_username', models.CharField(help_text='Recipient', max_length=30)),
                ('message', models.CharField(help_text='message', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_no', models.AutoField(primary_key=True, serialize=False)),
                ('current_projects', models.CharField(default='No current Projects', help_text='Projects', max_length=1000)),
                ('company', models.CharField(help_text='Company name', max_length=30)),
                ('phone', models.CharField(help_text='Company phone number', max_length=20)),
                ('location', models.CharField(help_text='Company location', max_length=20)),
                ('country', models.CharField(help_text='Company country', max_length=30)),
                ('sector', models.CharField(help_text='Company sector', max_length=30)),
                ('industry', models.CharField(help_text='Company industry', max_length=30)),
                ('description', models.CharField(default='No description yet', help_text='Project description', max_length=3000)),
                ('is_private', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='send_from_username',
            field=models.ForeignKey(help_text='Sender', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
