# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_username', models.CharField(help_text='Recipient', max_length=30)),
                ('message', models.CharField(help_text='message', max_length=5000)),
                ('send_from_username', models.ForeignKey(help_text='Sender', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
