# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_report_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='send_from_username',
        ),
        migrations.RemoveField(
            model_name='message',
            name='send_to_username',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='', help_text='Receiver', max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='', help_text='Sender', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='', help_text='message', max_length=5000),
        ),
    ]
