# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171112_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_investor',
            field=models.BooleanField(default=False),
        ),
    ]
