# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_report_current_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AddField(
            model_name='report',
            name='init_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='report_no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
