# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_profile_is_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='funding_goal',
            field=models.CharField(default='10,000', help_text='Funding goal', max_length=20),
        ),
    ]
