# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_message_encrypt'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=0, help_text='upvotes')),
                ('project_name', models.CharField(help_text='project name', max_length=100)),
                ('project_description', models.CharField(help_text='project description', max_length=1000)),
            ],
        ),
    ]
