# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('catalog', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
