# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_project_user_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_set',
        ),
    ]
