# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_project_user_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_company',
            field=models.CharField(default='', help_text='project name', max_length=100),
        ),
    ]
