# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_project_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
