# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_report_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='', help_text='message', max_length=500),
        ),
    ]
