# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20171128_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
