# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20171128_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
