# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20171130_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='sender name', max_length=100)),
                ('comment', models.CharField(help_text='comment', max_length=2000)),
                ('report_id', models.IntegerField(default=0, help_text='report id')),
            ],
        ),
    ]
