# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20171130_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_rate', models.IntegerField(default=0, help_text='report rating')),
                ('report_id', models.IntegerField(default=0, help_text='report id')),
                ('rate_by', models.CharField(help_text='rater username', max_length=100)),
            ],
        ),
    ]
