# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_reportrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrate',
            name='report_rate',
            field=models.FloatField(default=0.0, help_text='report rating'),
        ),
    ]
