# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20171201_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
