# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company name', max_length=30)),
                ('phone', models.CharField(help_text='Company phone number', max_length=20)),
                ('location', models.CharField(help_text='Company location', max_length=20)),
                ('country', models.CharField(help_text='Company country', max_length=30)),
                ('sector', models.CharField(help_text='Company sector', max_length=30)),
                ('industry', models.CharField(help_text='Company industry', max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
