# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
