# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_report_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='current_projects',
            field=models.CharField(default='No current Projects', help_text='Projects', max_length=1000),
        ),
    ]
